# version: '3'

# services:
#   django:
#     build: .
#     container_name: django
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - 8000:8000
#     depends_on:
#       - pgdb

#   pgdb:
#     image: postgres
#     container_name: pgdb
#     volumes:
#       - pgdbdata:/var/lib/postgresql/data/
#     expose:
#       - 5432
#   redis:
#     image: redis
#     expose:
#       - 6379
# volumes:
#   pgdbdata: null
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - :5432

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_PORT=5433
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    expose:
      - 6379