# Generated by Django 5.1.3 on 2024-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('manager', 'Менеджер'), ('CRMadmin', 'CRM-администратор')], max_length=100)),
                ('offer', models.BooleanField(default=False)),
                ('avatar', models.ImageField(upload_to='static/icons')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
