# Generated by Django 5.1.3 on 2024-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_selection', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/icons/default_icon.png', upload_to='static/icons'),
        ),
    ]
